# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CheckList_Admin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'MBProgressHUD'
  pod 'SwiftyJSON'
  pod 'SDWebImage'
  pod 'IQKeyboardManagerSwift'
  pod 'Alamofire', '~> 4.9.0'
  pod 'iOSDropDown'
  pod 'PieCharts'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'CropViewController'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
 end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
         end
      end
   end
end
