# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CheckList_Admin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'MBProgressHUD'
  pod 'SwiftyJSON'
  pod 'SDWebImage'
  pod 'IQKeyboardManagerSwift'
  pod 'Alamofire', '~> 4.9.0'
  pod 'iOSDropDown'
  pod 'PieCharts'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'CropViewController'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
 end
